# -*- coding: utf-8 -*-
"""p1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14D8JEGNm84THm4VB_eMPOsG7yDtXWMQz
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/ecommerce_sales.csv")
display(df)

print(df.shape)

df.head()

df.info()

df.describe(include='all')

ecommerce_cleaned = df.copy()

df.columns

df.info()

df.isnull().sum()

df['email']=df['email'].fillna('NA')

df['quantity']

df['quantity']=df['quantity'].bfill()
df['quantity']
df.isnull().sum()

m=np.mean(df['price'])
df['price']=df['price'].fillna(m)
df['price']
df.isnull().sum()

df['city']=df['city'].ffill()
df['city']
df.isnull().sum()

df['pincode']=df['pincode'].ffill()
df['pincode']
df.isnull().sum()

df['payment_method']=df['payment_method'].fillna("COD")
df.isnull().sum()

df.duplicated().sum()
df[df.duplicated()]

df.drop_duplicates()

for i in df.columns:
  print(i,df[i].unique())

df['city']=df['city'].replace('Hyd','Hyderabad')
df['city']=df['city'].replace('Pune','Chennai')
df['city']=df['city'].replace('Bang','Bangalore')
df['city'].unique()

df['payment_method']=df['payment_method'].replace('NetBanking','Net Banking')
df['payment_method']=df['payment_method'].replace('Upi','UPI')
df['payment_method']=df['payment_method'].replace('Credit card','Credit Card')
df['payment_method'].unique()

for i in df.columns:
  print(i,df[i].unique())

df.duplicated().sum()

df.drop_duplicates()

df.info()

df['quantity']=df['quantity'].astype('int64')
df['price']=df['price'].astype('float64')
df['pincode']=df['pincode'].astype('int64')
df.info()

df['order_date'].unique()

print(df.to_string())

df['order_date'] = pd.to_datetime(df['order_date'])
df['order_date']

print(df.to_csv('ecommerce_sales.csv'))


#extra code
import pandas as pd

# Load dataset
df = pd.read_csv("ecommerce_data.csv")

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Remove rows with missing values
df.dropna(inplace=True)

# Convert Date column to datetime
df["Date"] = pd.to_datetime(df["Date"])

# Remove leading/trailing spaces from text columns
text_columns = ["Customer Name", "Category"]

for col in text_columns:
    df[col] = df[col].str.strip()

# Convert Sales and Profit to numeric
df["Sales"] = pd.to_numeric(df["Sales"], errors="coerce")
df["Profit"] = pd.to_numeric(df["Profit"], errors="coerce")

# Save cleaned dataset
df.to_csv("cleaned_ecommerce_data.csv", index=False)

print("Data cleaning completed successfully.")